Repository SsgStudy/ssg-wms, pull requests merged in 2024-02, with the labels that each got.

#1 [CREATE] README.md
  README.md
Labels: DOCE

#2 [UPDATE] README.md
  README.md
Labels: DOCE

#3 [chore] README.md 팀명 추가
  README.md
Labels: DOCE

#4 [CHORE] README 팀명 삭제
  README.md
Labels: DOCE

#5 [REFACTOR] DB 접속 정보 분리 및 싱글톤 적용
  .gitignore
  src/test/testmain.java
  src/util/DbConnection.java
  ssg-wms.iml
Labels: REFACTOR

#6 [DOCS] README파일 추가 및 디렉토리 설정
  src/config/README_CONFIG.md
  src/controller/README_CONTROLLER.md
  src/dao/README_DAO.md
  src/service/README_SERVICE.md
  src/util/README_UTIL.md
  src/vo/README_VO.md
Labels: DOCE, CHORE

#7 [FEAT] ENUM 클래스 추가
  src/controller/IncomingController.java
  src/dao/IncomingDAO.java
  src/dao/IncomingDAOImpl.java
  src/service/IncomigService.java
  src/service/IncomingServiceImpl.java
  src/test/Main.java
  src/test/testmain.java
  src/util/DbConnection.java
  src/util/enumcollect/DispatchStatusEnum.java
  src/util/enumcollect/InventoryChangeTypeEnum.java
  src/util/enumcollect/MemberEnum.java
  src/util/enumcollect/OrderCollectionTypeEnum.java
  src/util/enumcollect/OrderStatusEnum.java
  src/util/enumcollect/SalesStatus.java
  src/util/enumcollect/StockCategoryEnum.java
  src/util/enumcollect/StockStatusEnum.java
  src/util/enumcollect/WaybillTypeEnum.java
Labels: FEAT

#8 [FEAT] 발주 목록 조회
  src/controller/OrderController.java
  src/dao/OrderDAO.java
  src/dao/OrderDAOImpl.java
  src/service/OrderService.java
  src/service/OrderServiceImpl.java
  src/test/OrderMain.java
  src/vo/IncomingVO.java
  src/vo/OrderVO.java
  ssg-wms.iml
Labels: FEAT

#10 [FEAT] 회원 목록 조회 및 회원정보 수정
  src/dao/MemberManagementDao.java
  src/dao/MemberManagementDaoImpl.java
  src/service/MemberService.java
  src/service/MemberServicelmpl.java
  src/vo/Member.java
Labels: FEAT

#9 [FEAT] 창고 등록 및 조회
  src/dao/WareHouseDao.java
  src/daoImpl/WareHouseDaoImpl.java
  src/service/WareHouseService.java
  src/serviceImpl/WareHouseServiceImpl.java
  src/vo/WareHouse.java
  src/vo/WareHouseZone.java
Labels: FEAT

#11 [FEAT] 입고 관리 기능 전체 구현
  src/controller/IncomingController.java
  src/controller/OrderController.java
  src/dao/IncomingDAO.java
  src/dao/IncomingDAOImpl.java
  src/service/IncomigService.java
  src/service/IncomingServiceImpl.java
  src/serviceImpl/WareHouseServiceImpl.java
  src/test/OrderMain.java
  src/vo/DetailedIncomingVO.java
Labels: FEAT, STYLE

#12 [FEAT] 로그인 관리 기능 구현
  src/dao/LoginManagementDAO.java
  src/dao/LoginManagementDAOImpl.java
  src/service/LoginManagementService.java
  src/service/LoginManagementServiceImpl.java
  src/vo/MemberVO.java
Labels: FEAT

#15 [FEAT] 상품 등록 기능 구현
  src/controller/ProductManagementController.java
  src/dao/ProductManagementDao.java
  src/dao/ProductManagementDaoImpl.java
  src/service/ProductService.java
  src/service/ProductServiceImpl.java
  src/vo/Category.java
  src/vo/Product.java
Labels: FEAT, STYLE, REFACTOR

#16 [FEAT] 출고 관리 전체 구현
  src/controller/OutgoingController.java
  src/dao/OutgoingDAO.java
  src/dao/OutgoingDAOImpl.java
  src/service/OutgoingService.java
  src/service/OutgoingServiceImpl.java
  src/test/OutgoingMain.java
  src/util/AsciiPrinter.java
  src/vo/InventoryVO.java
  src/vo/OutgoingInstVO.java
  src/vo/OutgoingVO.java
Labels: FEAT

#18 [FEAT] 주문 수집, 확정, 취소 로직 변경
  src/controller/PurchaseController.java
  src/dao/PurchaseDAO.java
  src/dao/PurchaseDAOImpl.java
  src/service/PurchaseService.java
  src/service/PurchaseServiceImpl.java
  src/util/enumcollect/PurchaseClaimEnum.java
  src/util/enumcollect/PurchaseEnum.java
  src/vo/PurchaseVO.java
Labels: FEAT

#20 [FEAT] 로거 추가 및 로그인 상태 및 메소드 권한 접근 제어
  src/controller/MemberController.java
  src/controller/OrderController.java
  src/dao/LoginManagementDAO.java
  src/dao/LoginManagementDAOImpl.java
  src/dao/OutgoingDAOImpl.java
  src/service/LoginManagementService.java
  src/service/LoginManagementServiceImpl.java
  src/test/OrderMain.java
Labels: FEAT, STYLE, REFACTOR

#24 [FEAT] 메인 메뉴 구성 및 싱글톤 적용
  src/controller/IncomingController.java
  src/controller/InvoiceController.java
  src/controller/MemberController.java
  src/controller/MembrManagemntController.java
  src/controller/OutgoingController.java
  src/controller/ProductManagementController.java
  src/controller/WareHouseController.java
  src/dao/InvoiceDaoImpl.java
  src/dao/MemberManagementDaoImpl.java
  src/dao/OutgoingDAOImpl.java
  src/dao/ProductManagementDaoImpl.java
  src/dao/WareHouseDaoImpl.java
  src/launcher/mainLauncher.java
  src/service/IncomingServiceImpl.java
  src/service/InvoiceServiceImpl.java
  src/service/MemberServicelmpl.java
  src/service/OutgoingServiceImpl.java
  src/service/ProductServiceImpl.java
  src/service/WareHouseServiceImpl.java
Labels: FEAT, FIX, STYLE, REFACTOR

#25 [FEAT] 재고 관리 전체 구현
  src/controller/InventoryController.java
  src/dao/InventoryAdjustmentDAO.java
  src/dao/InventoryAdjustmentDAOImpl.java
  src/dao/InventoryMovementDAO.java
  src/dao/InventoryMovementDAOImpl.java
  src/dao/InventoryQueryDAO.java
  src/dao/InventoryQueryDAOImpl.java
  src/service/InventoryAdjustmentService.java
  src/service/InventoryAdjustmentServiceImpl.java
  src/service/InventoryMovementService.java
  src/service/InventoryMovementServiceImpl.java
  src/service/InventoryQueryService.java
  src/service/InventoryQueryServiceImpl.java
  src/util/enumcollect/InventoryChangeTypeEnum.java
  src/vo/CategoryVO.java
  src/vo/InventoryVO.java
  src/vo/ProductInventoryCategoryVO.java
  src/vo/ProductInventoryWarehouseVO.java
Labels: FEAT, FIX, STYLE, REFACTOR

#22 [FIX] 송장 QR코드 내용 항목 추가
  src/controller/WareHouseController.java
  src/dao/InvoiceDaoImpl.java
  src/dao/WareHouseDao.java
  src/dao/WareHouseDaoImpl.java
  src/service/InvoiceServiceImpl.java
  src/service/WareHouseServiceImpl.java
  src/vo/Invoice.java
Labels: FIX

#26 [FIX] import 구문 수정
  src/controller/WareHouseController.java
Labels: FIX

#30 [REFACTOR] 메인 메뉴 병합 및 주문관리 싱글톤패턴 리팩토링
  src/controller/MembrManagemntController.java
  src/controller/PurchaseController.java
  src/dao/IncomingDAO.java
  src/dao/InventoryAdjustmentDAOImpl.java
  src/dao/InvoiceDaoImpl.java
  src/dao/OutgoingDAO.java
  src/dao/OutgoingDAOImpl.java
  src/dao/ProductManagementDaoImpl.java
  src/dao/PurchaseDAOImpl.java
  src/launcher/mainLauncher.java
  src/service/InvoiceServiceImpl.java
  src/service/MemberServicelmpl.java
  src/service/OutgoingService.java
  src/service/OutgoingServiceImpl.java
  src/service/ProductServiceImpl.java
  src/service/PurchaseServiceImpl.java
  src/test/OutgoingMain.java
Labels: FEAT, REFACTOR

#31 [REFACTOR] 메뉴 뎁스 수정 및 회원 정보 유지 수정
  src/controller/IncomingController.java
  src/controller/InventoryController.java
  src/controller/InvoiceController.java
  src/controller/MembrManagemntController.java
  src/controller/OutgoingController.java
  src/controller/ProductManagementController.java
  src/controller/PurchaseController.java
  src/controller/WareHouseController.java
  src/dao/MemberManagementDaoImpl.java
  src/dao/WareHouseDaoImpl.java
  src/service/WareHouseService.java
  src/service/WareHouseServiceImpl.java
Labels: FIX, REFACTOR

#34 [FIX] 재고 관리 메뉴 뎁스 및 재고 조회 구문 수정
  src/controller/InventoryController.java
  src/dao/InventoryAdjustmentDAOImpl.java
  src/dao/InventoryMovementDAOImpl.java
  src/dao/InventoryQueryDAOImpl.java
Labels: FIX, REFACTOR

#35 [REFACTOR] 메인 메뉴 병합 및 발주관리 관련 싱글톤패턴 리팩토링
  src/controller/InvoiceController.java
  src/controller/OrderController.java
  src/controller/OutgoingController.java
  src/dao/OrderDAO.java
  src/launcher/mainLauncher.java
  src/service/InvoiceService.java
  src/service/InvoiceServiceImpl.java
  src/service/OrderServiceImpl.java
  src/service/PurchaseServiceImpl.java
Labels: FEAT, REFACTOR

#36 [FEAT] 선택 박스 추가 및 코드 정리
  src/controller/MemberController.java
  src/controller/MembrManagemntController.java
  src/controller/OutgoingController.java
  src/controller/PurchaseController.java
  src/dao/MemberManagementDaoImpl.java
  src/launcher/mainLauncher.java
  src/util/MenuBoxPrinter.java
Labels: FEAT, FIX, STYLE, REFACTOR

#37 [REFACTOR] 주문 서비스 컨트롤러 구조 수정
  src/controller/PurchaseController.java
  src/dao/OrderDAOImpl.java
  src/dao/PurchaseDAO.java
  src/dao/PurchaseDAOImpl.java
  src/service/PurchaseService.java
  src/service/PurchaseServiceImpl.java
Labels: FIX, STYLE, REFACTOR

#40 [FIX] 상품관리 카테고리 선택 수정 및 송장관리 메뉴 호출 수정
  src/controller/InvoiceController.java
  src/controller/ProductManagementController.java
Labels: FIX

#39 [STYLE] 관리메뉴별 디자인 추가
  src/controller/IncomingController.java
  src/controller/InventoryController.java
  src/controller/MembrManagemntController.java
  src/controller/OrderController.java
  src/controller/OutgoingController.java
  src/controller/ProductManagementController.java
  src/controller/PurchaseController.java
  src/controller/WareHouseController.java
  src/launcher/mainLauncher.java
  src/util/MenuBoxPrinter.java
Labels: FEAT, STYLE, REFACTOR

#42 [FEAT] 컨트롤러 내 메소드 별 접근 권한 설정
  src/controller/IncomingController.java
  src/controller/InventoryController.java
  src/controller/InvoiceController.java
  src/controller/OrderController.java
  src/controller/OutgoingController.java
  src/controller/ProductManagementController.java
  src/controller/PurchaseController.java
  src/controller/WareHouseController.java
  src/dao/IncomingDAOImpl.java
  src/dao/InventoryAdjustmentDAOImpl.java
  src/dao/InventoryMovementDAOImpl.java
  src/dao/InventoryQueryDAOImpl.java
  src/dao/InvoiceDaoImpl.java
  src/dao/LoginManagementDAOImpl.java
  src/dao/MemberManagementDaoImpl.java
  src/dao/OrderDAOImpl.java
  src/dao/OutgoingDAOImpl.java
  src/dao/ProductManagementDaoImpl.java
  src/util/MenuBoxPrinter.java
Labels: FEAT, FIX, STYLE, REFACTOR

#43 [FIX] 발주 등록 메뉴 분기 처리 수정 및 송장 조회 메소드 호출 방식 수정
  src/controller/InvoiceController.java
  src/controller/OrderController.java
Labels: FIX, REFACTOR

#44 [FIX] 반품 시 발생하는 오류 수정
  INV00000005.png
  src/controller/PurchaseController.java
  src/dao/OrderDAOImpl.java
  src/dao/PurchaseDAO.java
  src/dao/PurchaseDAOImpl.java
  src/service/PurchaseService.java
  src/service/PurchaseServiceImpl.java
Labels: FIX, CONFLICT

#45 [FIX] 출력문 오류 수정
  src/controller/MembrManagemntController.java
  src/controller/ProductManagementController.java
  src/controller/WareHouseController.java
Labels: FIX, STYLE

#47 [FIX] 발주 관리 메뉴 분기 처리 수정
  src/controller/OrderController.java
Labels: FIX

#48 [FIX] 재고 조정 권한 수정
  src/controller/InventoryController.java
  src/controller/OrderController.java
  src/controller/OutgoingController.java
Labels: FIX

#49 [STYLE] Javadoc 작성, 일반 주석 제거
  src/controller/IncomingController.java
  src/controller/InventoryController.java
  src/controller/InvoiceController.java
  src/controller/MemberController.java
  src/controller/MembrManagemntController.java
  src/controller/OrderController.java
  src/controller/OutgoingController.java
  src/controller/ProductManagementController.java
  src/controller/PurchaseController.java
  src/controller/WareHouseController.java
  src/service/IncomigService.java
  src/service/IncomingServiceImpl.java
  src/service/InventoryAdjustmentService.java
  src/service/InventoryAdjustmentServiceImpl.java
  src/service/InventoryMovementService.java
  src/service/InventoryMovementServiceImpl.java
  src/service/InventoryQueryService.java
  src/service/InventoryQueryServiceImpl.java
  src/service/InvoiceService.java
  src/service/InvoiceServiceImpl.java
  src/service/LoginManagementService.java
  src/service/LoginManagementServiceImpl.java
  src/service/MemberService.java
  src/service/MemberServicelmpl.java
  src/service/OrderService.java
  src/service/OrderServiceImpl.java
  src/service/OutgoingService.java
  src/service/OutgoingServiceImpl.java
  src/service/ProductService.java
  src/service/ProductServiceImpl.java
  src/service/PurchaseService.java
  src/service/PurchaseServiceImpl.java
  src/service/WareHouseService.java
  src/service/WareHouseServiceImpl.java
Labels: STYLE

#50 [FIX] 테스트 과정에서 발견한 오류 수정
  src/controller/OrderController.java
  src/controller/OutgoingController.java
  src/controller/PurchaseController.java
  src/dao/OrderDAOImpl.java
  src/dao/OutgoingDAOImpl.java
  src/dao/PurchaseDAO.java
  src/dao/PurchaseDAOImpl.java
  src/launcher/mainLauncher.java
  src/service/InvoiceServiceImpl.java
  src/service/PurchaseService.java
  src/service/PurchaseServiceImpl.java
Labels: FEAT, FIX

#51 [STYLE] Javadoc 추가
  src/controller/OutgoingController.java
  src/controller/PurchaseController.java
  src/service/InvoiceServiceImpl.java
  src/service/PurchaseService.java
  src/service/PurchaseServiceImpl.java
Labels: STYLE
